version: "3"

services:

  nginx-elastic-auth:
    image: nginx:1.21.1
    restart: unless-stopped
    volumes:
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf
      - ./elasticsearch/.htpasswd:/etc/nginx/.htpasswd
    ## To automatically generate the user and password in .htpasswd:
    #   - AUTH_USER=${AUTH_USER:-elastic}
    #   - AUTH_PASSWORD=${AUTH_PASSWORD:-elastic}
    # entrypoint: "bash -c 'echo -n $AUTH_USER: >> /etc/nginx/.htpasswd && echo $AUTH_PASSWORD | openssl passwd -stdin -apr1 >> /etc/nginx/.htpasswd && /docker-entrypoint.sh nginx'"
    # Or do it before: htpasswd -Bbn elastic yourpassword > elasticsearch/.htpasswd


  elasticsearch:
    image: elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}


  website:
    build: ./website
    restart: unless-stopped


  update-pipeline:
    build: ./etl
    # profiles: ["runner"]
    depends_on: 
      - elasticsearch
    environment: 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-dba}
    # entrypoint: "bash -c 'pip install -r /etl/requirements.txt && python3 /etl/lsr_csv_to_elastic.py'"
    volumes:
      - ./etl:/root



  # express-server:
  #   build: ./server
  #   restart: unless-stopped
  #   environment:
  #     - ELASTIC_URL=http://elasticsearch:9200
