version: "3"

services:

  nginx:
    image: nginx
    container_name: bio2kg-prefixes-elastic-nginx
    volumes: 
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf
      - ./elasticsearch/nginx.conf:/etc/nginx/.htpasswd
    ports:
      - 8080:8080
    environment:   
      - VIRTUAL_HOST=elastic.prefixes.bio2kg.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=elastic.prefixes.bio2kg.137.120.31.102.nip.io
      - VIRTUAL_PORT=8080
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  elasticsearch:
    container_name: bio2kg-prefixes-elasticsearch
    image: elasticsearch:7.13.2
    restart: unless-stopped
    environment:   
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      # - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      # - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - VIRTUAL_HOST=elastic.prefixes.bio2kg.137.120.31.102.nip.io
      # - LETSENCRYPT_HOST=elastic.prefixes.bio2kg.137.120.31.102.nip.io
      # - VIRTUAL_PORT=9200
      # Also 9300
    # ports: 
    #   - 9200:9200
    volumes:
      - /data/bio2kg/prefixes/elasticsearch:/usr/share/elasticsearch/data

  nodejs:
    build: ./website
    container_name: bio2kg-prefixes-website
    environment:   
      - VIRTUAL_HOST=prefixes.bio2kg.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=prefixes.bio2kg.137.120.31.102.nip.io
      - VIRTUAL_PORT=3000
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    # ports:
    #   - 3000:3000