version: "3"
# version: "3.9"

services:

  nginx-elastic-auth:
    environment:   
      - VIRTUAL_HOST=elastic.registry.bio2kg.org
      - LETSENCRYPT_HOST=elastic.registry.bio2kg.org
      - VIRTUAL_PORT=8080

  elasticsearch:
    volumes:
      - /data/bio2kg/registry/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"


  express-server:
    environment:
      - VIRTUAL_HOST=registry.bio2kg.org
      - LETSENCRYPT_HOST=registry.bio2kg.org
      - VIRTUAL_PORT=4000


  virtuoso:
    volumes:
      - /data/bio2kg/registry/virtuoso:/database
    environment:
      # Deployed using https://github.com/nginx-proxy
      - VIRTUAL_PORT=8890
      - VIRTUAL_HOST=data.registry.bio2kg.org
      - LETSENCRYPT_HOST=data.registry.bio2kg.org

      - VIRT_URIQA_DefaultHost=data.registry.bio2kg.org
      - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_Parameters_NumberOfBuffers=10880000 # For 128G systems
      # - VIRT_Parameters_MaxDirtyBuffers=8000000
      # - VIRT_Database_ErrorLogLevel=2 # default: 7 is maximum logs
