# version: "3.9"
version: "3"

services:

  nginx-elastic-auth:
    image: nginx
    container_name: bio2kg-registry-elastic-nginx
    restart: unless-stopped
    volumes: 
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf
      - ./elasticsearch/.htpasswd:/etc/nginx/.htpasswd
    # ports:
    #   - 8080:8080
    environment:   
      - VIRTUAL_HOST=elastic.registry.bio2kg.org
      - LETSENCRYPT_HOST=elastic.registry.bio2kg.org
      - VIRTUAL_PORT=8080

  elasticsearch:
    container_name: bio2kg-registry-elasticsearch
    image: elasticsearch:7.13.2
    restart: unless-stopped
    environment:   
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    # ports: 
    #   - 9200:9200
    volumes:
      - /data/bio2kg/registry/elasticsearch:/usr/share/elasticsearch/data
      
  # nextjs-website:
  #   build: ./website
  #   container_name: bio2kg-registry-website
  #   restart: unless-stopped
  #   environment:
  #     - VIRTUAL_HOST=registry.bio2kg.org
  #     - LETSENCRYPT_HOST=registry.bio2kg.org
  #     - VIRTUAL_PORT=3000
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    # ports:
    #   - 3000:3000

  express-server:
    build: ./server
    container_name: bio2kg-registry-server
    restart: unless-stopped
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - VIRTUAL_HOST=registry.bio2kg.org
      - LETSENCRYPT_HOST=registry.bio2kg.org
      - VIRTUAL_PORT=4000

  update-pipeline:
    build: ./etl
    # image: python:3.8
    container_name: bio2kg-registry-update-pipeline
    # profiles: ["runner"]
    depends_on: 
      - elasticsearch
    environment: 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-dba}
    # entrypoint: "bash -c 'pip install -r /etl/requirements.txt && python3 /etl/lsr_csv_to_elastic.py'"
    volumes:
      - ./etl:/root


  virtuoso:
    container_name: bio2kg-registry-virtuoso
    image: openlink/virtuoso-opensource-7:latest
    # See also: https://hub.docker.com/r/markw/ldp_server
    # https://community.openlinksw.com/t/permissions-on-ldp-containers-and-resources/290/14
    # Download VAD packages: ODS Framework and Briefcase
    # http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/7.2/
    restart: unless-stopped
    volumes:
      - /data/bio2kg/registry/virtuoso:/database
    environment:
      # Deployed using https://github.com/nginx-proxy
      - VIRTUAL_PORT=8890
      - VIRTUAL_HOST=data.registry.bio2kg.org
      - LETSENCRYPT_HOST=data.registry.bio2kg.org
      - VIRT_URIQA_DefaultHost=data.registry.bio2kg.org
      - DBA_PASSWORD=${ELASTIC_PASSWORD:-dba}
      - DAV_PASSWORD=${ELASTIC_PASSWORD:-dba}
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/bio2kg
      # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
      # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
      # https://github.com/tenforce/docker-virtuoso/blob/master/virtuoso.ini
      - VIRT_Database_ErrorLogLevel=2 # default: 7 is maximum logs
      - VIRT_HTTPServer_HTTPThreadSize=280000
      # - VIRT_URIQA_DynamicLocal=1
      # - VIRT_Parameters_DirsAllowed=., /data, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      # Large dataset config
      - VIRT_SPARQL_ResultSetMaxRows=1048576
      - VIRT_SPARQL_MaxQueryCostEstimationTime=200000
      - VIRT_SPARQL_MaxQueryExecutionTime=1000000
      - VIRT_Database_MaxCheckpointRemap=125000
      - VIRT_TempDatabase_MaxCheckpointRemap=125000
      - VIRT_Parameters_TempDBSize=100000000
      - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_Parameters_NumberOfBuffers=10880000 # For 128G systems
      # - VIRT_Parameters_MaxDirtyBuffers=8000000
      - VIRT_SPARQL_ShortenLongURIs=1
      - VIRT_SPARQL_MaxCacheExpiration=1
      - VIRT_SPARQL_ExternalQuerySource=1
      - VIRT_SPARQL_ExternalXsltSource=1
    # ports:
    #   - 8890:8890
    #   - 1111:1111