version: "3"
# version: "3.9"

services:

  nginx-elastic-auth:
    image: nginx:1.21.1
    container_name: bio2kg-registry-elastic-nginx
    restart: unless-stopped
    volumes:
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf
      - ./elasticsearch/.htpasswd:/etc/nginx/.htpasswd
    ## To automatically generate the user and password in .htpasswd:
    #   - AUTH_USER=${AUTH_USER:-elastic}
    #   - AUTH_PASSWORD=${AUTH_PASSWORD:-elastic}
    # entrypoint: "bash -c 'echo -n $AUTH_USER: >> /etc/nginx/.htpasswd && echo $AUTH_PASSWORD | openssl passwd -stdin -apr1 >> /etc/nginx/.htpasswd && /docker-entrypoint.sh nginx'"


  elasticsearch:
    container_name: bio2kg-registry-elasticsearch
    image: elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}


  express-server:
    build: ./server
    container_name: bio2kg-registry-server
    restart: unless-stopped
    environment:
      - ELASTIC_URL=http://elasticsearch:9200


  update-pipeline:
    build: ./etl
    container_name: bio2kg-registry-update-pipeline
    # profiles: ["runner"]
    depends_on: 
      - elasticsearch
    environment: 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-dba}
    # entrypoint: "bash -c 'pip install -r /etl/requirements.txt && python3 /etl/lsr_csv_to_elastic.py'"
    volumes:
      - ./etl:/root


  # virtuoso:
  #   container_name: bio2kg-registry-virtuoso
  #   image: openlink/virtuoso-opensource-7:latest
  #   # See also: https://hub.docker.com/r/markw/ldp_server
  #   # https://community.openlinksw.com/t/permissions-on-ldp-containers-and-resources/290/14
  #   # Download VAD packages: ODS Framework and Briefcase
  #   # http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/7.2/
  #   restart: unless-stopped
  #   environment:
  #     # - VIRT_URIQA_DefaultHost=data.registry.bio2kg.org
  #     - DBA_PASSWORD=${ELASTIC_PASSWORD:-dba}
  #     - DAV_PASSWORD=${ELASTIC_PASSWORD:-dba}
  #     - SPARQL_UPDATE=true
  #     - DEFAULT_GRAPH=https://w3id.org/bio2kg
  #     # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
  #     # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
  #     # https://github.com/tenforce/docker-virtuoso/blob/master/virtuoso.ini
  #     - VIRT_Database_ErrorLogLevel=2 # default: 7 is maximum logs
  #     # - VIRT_HTTPServer_HTTPThreadSize=280000
  #     # - VIRT_URIQA_DynamicLocal=1
  #     # - VIRT_Parameters_DirsAllowed=., /data, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
  #     # Large dataset config
  #     # - VIRT_SPARQL_ResultSetMaxRows=1048576
  #     # - VIRT_SPARQL_MaxQueryCostEstimationTime=200000
  #     # - VIRT_SPARQL_MaxQueryExecutionTime=1000000
  #     # - VIRT_Database_MaxCheckpointRemap=125000
  #     # - VIRT_TempDatabase_MaxCheckpointRemap=125000
  #     # - VIRT_Parameters_TempDBSize=100000000
  #     # - VIRT_SPARQL_ShortenLongURIs=1
  #     # - VIRT_SPARQL_MaxCacheExpiration=1
  #     # - VIRT_SPARQL_ExternalQuerySource=1
  #     # - VIRT_SPARQL_ExternalXsltSource=1
