version: "3"

services:

  nginx-elastic-auth:
    image: nginx
    container_name: bio2kg-registry-elastic-nginx
    volumes: 
      - ./elasticsearch/nginx.conf:/etc/nginx/nginx.conf
      - ./elasticsearch/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - 8080:8080
    environment:   
      - VIRTUAL_HOST=elastic.registry.bio2kg.org
      - LETSENCRYPT_HOST=elastic.registry.bio2kg.org
      - VIRTUAL_PORT=8080

  elasticsearch:
    container_name: bio2kg-registry-elasticsearch
    image: elasticsearch:7.13.2
    restart: unless-stopped
    environment:   
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      # - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      # - xpack.security.enabled=true
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - VIRTUAL_HOST=elastic.registry.bio2kg.org
      # - LETSENCRYPT_HOST=elastic.registry.bio2kg.org
      # - VIRTUAL_PORT=9200
    # ports: 
    #   - 9200:9200
    volumes:
      - /data/bio2kg/registry/elasticsearch:/usr/share/elasticsearch/data

  nodejs-website:
    build: ./website
    container_name: bio2kg-registry-website
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=registry.bio2kg.org
      - LETSENCRYPT_HOST=registry.bio2kg.org
      - VIRTUAL_PORT=3000
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    # ports:
    #   - 3000:3000

  update-pipeline:
    image: python:3.8
    container_name: bio2kg-registry-update-pipeline
    depends_on: 
      - elasticsearch
    entrypoint: "bash -c 'pip install -r /etl/requirements.txt && python3 /etl/lsr_csv_to_elastic.py'"
    volumes:
      - ./etl:/etl
      